services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      JENKINS_ADMIN_PASSWORD: "admin123"
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    volumes:
      # Jenkins home → keep all configs, jobs, plugins (visible on E:)
      - "E:\\Code\\Projects\\DevOps Project\\Volumes:/var/jenkins_home"
      # Logs → only logs (separate folder on E:)
      - "E:\\Code\\Projects\\DevOps Project\\Logs:/var/jenkins_home/logs"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
