version: "3.8"

services:
  jenkins-master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ../Volumes/jenkins-master:/var/jenkins_home
      - ../Logs/jenkins-master:/var/jenkins_home/logs
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - devops-net

networks:
  devops-net:
    driver: bridge